version: '3.7'

services:
  licensingservice:
    image: ostock/licensing-service:0.0.1-SNAPSHOT
    environment:
      CONFIGSERVER_URI: "http://192.168.1.171:8071"
    ports:
      - "8888:8888"


networks:
  backend:
    driver: bridge
