version: '3.7'

services:
  configservice:
    image: ostock/configserver:0.0.1-SNAPSHOT

    ports:
      - "8071:8071"

    environment:
      - "SPRING_PROFILE_ACTIVE=dev"

    networks:
      backend:
        aliases:
            - "configservice"

networks:
  backend:
    driver: bridge