spring:
  application:
    name: licensing-service
  profiles:
    active: dev
  config:
    import: configserver:http://configserver:8071

  main:
    allow-circular-references: true


management.endpoints.enabled-by-default: false
management.endpoint.health:
  enabled: true
  show-details: always


logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.optimagrowth: DEBUG